# import OS image
FROM ubuntu:latest

LABEL maintainer="Bl4ckr053"




# create user with sudo privileges
RUN groupadd -r user && useradd -r -g sudo user

# Request passwd 
RUN passwd

# Prevent user from logging in to root account
# RUN chsh -s /usr/sbin/nologin root

# Environment Variables
ENV HOME /home/user
ENV DEBIAN_FRONTEND=noninteractive


# Working Directory
WORKDIR /home/user
RUN mkdir ${HOME}/OSINT

# Install kali essentials
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    tilix \
    gcc \
    iputils-ping\
    git \
    vim \
    wget \
    awscli \
    tzdata \
    curl \
    make \
    nmap \
    theHarvester \
    dirb \
    whois \
    python \
    python-pip \
    python3 \
    python3-pip \
    perl \
    nikto \
    dnsutils \
    # dig
    dig \
    net-tools \
    # enum4linux
    enum4linux \
    # imapcket
    python3-impacket \
    zsh \
    nano \
    && rm -rf /var/lib/apt/lists/*

# Install katoolin

RUN cd ${HOME}/OSINT && \
    git clone https://github.com/LionSec/katoolin.git && \
    cd katoolin && \
    sudo chmod +x katoolin.py

# apt update 

RUN sudo apt update

# install recon tools

# sherlock
RUN cd ${HOME}/OSINT && \
    git clone https://github.com/sherlock-project/sherlock.git && \
    cd sherlock && \
    python3 -m pip install -r requirements.txt
    

#recon-ng
RUN cd ${HOME}/OSINT && \
    git clone https://github.com/lanmaster53/recon-ng.git && \
    cd recon-ng && \
    pip3 install -r REQUIREMENTS && \
    sudo chmod +x recon-ng && \
    ln -sf ${HOME}/OSINT/recon-ng/recon-ng /usr/local/bin/recon-ng

# CloudFlair
RUN cd ${HOME}/toolkit && \
    git clone https://github.com/christophetd/CloudFlair.git && \
    cd CloudFlair && \
    pip install -r requirements.txt && \
    chmod +x cloudflair.py && \
    ln -sf ${HOME}/toolkit/CloudFlair/cloudflair.py /usr/local/bin/cloudflair

# Git-tools
RUN cd ${HOME}/OSINT && \ 
    git clone https://github.com/internetwache/GitTools.git



# wafw00f
RUN cd ${HOME}/toolkit && \
    git clone https://github.com/enablesecurity/wafw00f.git && \
    cd wafw00f && \
    chmod +x setup.py && \
    python setup.py install